# Generated by Django 4.2.16 on 2025-08-02 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('Affecté', 'Affecté'), ('Hors service', 'Hors service')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('commentaires', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipements', models.ManyToManyField(blank=True, to='website.equipment')),
                ('types_materiel', models.ManyToManyField(to='website.materialtype')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.materialtype'),
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affecte_le', models.DateTimeField(auto_now_add=True)),
                ('retourne_le', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.materialrequest')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.equipment')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
