# Generated by Django 4.2.16 on 2025-08-02 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_number', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('sous_type', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('emplacement', models.CharField(max_length=200)),
                ('affecte', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('service', models.CharField(max_length=100)),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipements', models.ManyToManyField(to='website.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.CharField(max_length=100)),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.equipment')),
                ('fonctionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
