# Generated by Django 4.2.16 on 2025-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='history',
            field=models.BooleanField(default=False),
        ),
    ]
